name: Build

on: [push, pull_request]

jobs:
  patchjson:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B build_dir -DBUILD_APP=ON -DBUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build_dir --target patchjson_app --config ${{ matrix.build_type }}

      - name: Print version (Linux)
        if: runner.os != 'Windows'
        run: ./build_dir/app/patchjson --version

      - name: Print version (Windows)
        if: runner.os == 'Windows'
        run: .\build_dir\app\${{ matrix.build_type }}\patchjson.exe --version
