name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build_dir -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build_dir --target patchjson_tests --config ${{ matrix.build_type }}

      - name: Run tests
        run: ctest --test-dir build_dir/lib/tests --output-on-failure
